# android - https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/main/flutter/flutter-android-and-ios-yaml-demo-project/codemagic.yaml
# android - https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/#conclusion

#  https://codemagic.io/teams/62f38b6a033f9ce2596c014d -> Code signing identities

workflows:
  flutter-android:
    name: Flutter Android 
    instance_type: mac_mini_m2 # Other available machine types: mac_mini_m4, mac_studio_m4_max, linux_x2, linux_x4, windows_x2
    max_build_duration: 120
    triggering:
        events:
          - push
        branch_patterns:
          - pattern: main
            include: true
            source: true
    environment:
      android_signing:
        - nosleep_jks
      groups:
        - google_play # <-- (Includes GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: "com.sbdor.nosleep" # <-- Put your package name here
        GOOGLE_PLAY_TRACK: "production"
      flutter: 3.44.7
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set up key.properties
        script: |
          cat > "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Generate code (l10n, assets, build_runner)
        script: bash scripts/generate.bash
      - name: Setup Firebase CLI
        script: |
          curl -sL https://firebase.tools | bash
          firebase --version
      - name: Authenticate with Firebase
        script: |
          echo "$FIREBASE_CREDENTIALS_BASE64" | base64 --decode > $HOME/firebase_key.json
      - name: Create google_service_json for Android
        script: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > android/app/google-services.json
      - name: Config production json file setup
        script: |
          echo "$PRODUCTION_CONFIG_JSON_BASE64" | base64 --decode > config/production.json
      - name: Create firebase_options
        script: | 
          echo "$FIREBASE_OPTIONS_BASE64" | base64 --decode > lib/firebase_options.dart
      - name: Build AAB with Flutter
        script: |
            flutter build appbundle --release \
            --obfuscate \
            --split-debug-info=build/debug-info \
            --dart-define-from-file=config/production.json
      - name: Upload debug symbols to Crashlytics
        script: |
          firebase crashlytics:symbols:upload \
            --app=${{ secrets.ANDROID_FIREBASE_APP_ID }} \
            build/debug-info
    publishing:
      email:
        recipients:
          - avaz.shams.2002@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true